---
# Prepare the vault ini files for both PSMP and ADBridge
- name: Set full vault address
  set_fact:
    full_vault_addresses: "{{ vault_ip }}{% if dr_vault_ip is defined and dr_vault_ip != ''%},{{ dr_vault_ip }}{%endif%}"
- name: Prepare vault ini
  block:
    - name: Upload vault ini to the machine
      copy:
        src: "files/{{ psmp_vault_ini_name }}"
        dest: "{{ psmp_tmp_vault_ini_path }}"
    - name: Set vault name
      replace:
        path: "{{ psmp_tmp_vault_ini_path }}"
        regexp: "VAULT=.*"
        replace: "VAULT={{ vault_name }}"
    - name: Set vault address
      replace:
        path: "{{ psmp_tmp_vault_ini_path }}"
        regexp: "ADDRESS=.*"
        replace: "ADDRESS={{ full_vault_addresses }}"
    - name: Set vault port
      replace:
        path: "{{ psmp_tmp_vault_ini_path }}"
        regexp: "PORT=.*"
        replace: "PORT={{ vault_port }}"
    - name: Set vault timeout
      replace:
        path: "{{ psmp_tmp_vault_ini_path }}"
        regexp: "TIMEOUT=.*"
        replace: "TIMEOUT={{ vault_comm_timeout }}"
    - name: Set vault secured pre auth
      replace:
        path: "{{ psmp_tmp_vault_ini_path }}"
        regexp: "#PREAUTHSECUREDSESSION=.*"
        replace: "PREAUTHSECUREDSESSION=YES"
      when: psmp_preauth_secured_session
    - name: Set vault trust self signed certificates
      replace:
        path: "{{ psmp_tmp_vault_ini_path }}"
        regexp: "#TRUSTSSC=.*"
        replace: "TRUSTSSC=YES"
      when: psmp_selfsigned_certificates
    - name: Set vault trust self signed certificates for 3rd parties
      replace:
        path: "{{ psmp_tmp_vault_ini_path }}"
        regexp: "#ALLOWSSCFOR3PARTYAUTH=.*"
        replace: "ALLOWSSCFOR3PARTYAUTH=YES"
      when: psmp_selfsigned_certificates
  when: (psmp_create_psmp_env or psmp_create_adbridge_env)
- name: Copy vault ini file to PSMP
  copy:
    src: "{{ psmp_tmp_vault_ini_path }}"
    dest: "{{ psmp_vault_env_path }}/{{ psmp_vault_ini_name }}"
    remote_src: true
  when: psmp_create_psmp_env
- name: Copy vault ini file to PSMP ADB
  copy:
    src: "{{ psmp_tmp_vault_ini_path }}"
    dest: "{{ psmp_adb_vault_env_path }}/{{ psmp_vault_ini_name }}"
    remote_src: true
  when: psmp_create_adbridge_env
- name: Remove the temp vault ini file
  file:
    path: "{{ psmp_tmp_vault_ini_path }}"
    state: absent
  when: (psmp_create_psmp_env or psmp_create_adbridge_env)

# Create the credential file for the activation if password was given
- name: Create cred file for activation
  block:
    - name: "Run the CreateCredFile"
      command:
        argv:
          - "{{ psmp_createcredfile_path }}"
          - "{{ psmp_default_credfile_path }}"
          - "Password"
          - "-Username"
          - "{{ vault_username }}"
          - "-Password"
          - "{{ vault_password }}"
    - name: Set the vault credfile fact
      set_fact:
        credfile_path: "{{ psmp_default_credfile_path }}"
  when:
    - (vault_password != '')
    - (credfile_path == '')
